name: LAPRAS Card

permissions: write-all

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "RD0FNXS"
          # 以下オプション
          ICON_FIRST: "#03102f"
          ICON_SECOND: "#1688bf"
          BACKGROUND_FIRST: "#020e27"
          BACKGROUND_SECOND: "#0e5593"
          LANG: "en"
          CARD_WIDTH: "400"
          UPDATE_TIME: "true"
          README_FILE: "README.md"
          IS_CENTER: "true"
          ALTERNATIVE_TEXT: "Score of {SHARE_ID} on LAPRAS"